version: '3.4'

services:

  db:
    image: postgres:10.15-alpine
    networks:
      - db
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - envs/db/.env

  bot:
    build:
      context: .
    networks:
      - bot
      - db
    volumes:
      - ./:/app
    command: |
      /usr/bin/env sh -c "python main.py"
    env_file:
      - envs/bot/.env
      - envs/db/.env
    ports:
      - 3001:3001
    depends_on:
      - db

networks:
  db:
    driver: bridge
  bot:
    driver: bridge

volumes:
    dbdata:
      name: anon_talks_db
      driver: local
